version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  dockerapi:
    image: dockerapi:latest
    depends_on:
      - "postgres_image"
    build: 
      context: .
      dockerfile: TestProject/Dockerfile
    ports:
      - "8000:80"
    environment:
      courierDB: " host=host.docker.internal;port=5432;database=postgres;username=postgres;Password=qwerty229322; Pooling=true"
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "54320:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty229322
      POSTGRES_DB: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data/
    networks:
      - dockerapi-dev
volumes:
  db_volume:
  